### ISSUE TITLE
Problem with Device-Mockup

### ISSUE THREAD

**Issue by quisen** [BlackrockDigital/startbootstrap-new-age#11]
Im trying to change the mockup for "nexus_6" but it does not work... it appears a default macbook instead!

**Comment by davidtmiller** [comment]
Hmm interesting I will have to check this out.

**Comment by TheRealKira** [comment]
Also experiencing this bug. There are no nexus6 styles in device-mockups.css!

**Comment by davidtmiller** [comment]
I think that they just haven't added a Nexus 6 device yet, so it's an issue with the plugin and not the theme.
