### ISSUE TITLE
Icons colouring issue in older version of Firefox

### ISSUE THREAD

**Issue by antonio0** [BlackrockDigital/startbootstrap-new-age#17]
I opened the website on an older version of Firefox, 48.0.1 and the coloring of the icons is messed up. With the most recent version there is no problem. 

This is what I see, any way to fix this for users who haven't updated their browsers?

<img width="1215" alt="screenshot at apr 05 01-58-29" src="https://cloud.githubusercontent.com/assets/3067822/24684050/9776270c-19a3-11e7-942e-e62adc4299e4.png">

**Comment by davidtmiller** [comment]
This is just a bug it looks like with the gradient overlays. I'm choosing not to really support older browser versions, so even though it's clearly acting odd in older versions of Firefox I'd rather not dive into fixing something like this for an outdated browser.
