### ISSUE TITLE
How to update the min.css

### ISSUE THREAD

**Issue by artak1995** [BlackrockDigital/startbootstrap-new-age#20]
i modified the new-age.css, 
and I can't see the changes.
I guess I need to apply the changes to new-age.min.css
How can I apply? 
I would appreciate if you could answer :D

**Comment by AntoineMaalouf** [comment]
you can use a tool to minify your css after you're finished with your modifications

https://css.github.io/csso/csso.html

**Comment by davidtmiller** [comment]
Once downloading the template, run npm install, and then run gulp dev. After that the minified CSS should update automatically when you make changes to the SCSS files.
