### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by lguima** [BlackrockDigital/startbootstrap-new-age#34]
Could anyone help me to identify the color scheme used on this theme? I would like to use with a new one.

**Comment by atifwaqar** [comment]
Try playing with following code in `css/new-age.min.css`. Or you can simply find & replace following colors with your choice of color scheme.

These two are used in header Background `#dc2430` `#7b4397`
![image](https://user-images.githubusercontent.com/4388707/36277588-9590a006-1291-11e8-9c5f-5fd1840b477e.png)


Here are the rest of colors used in the css : 
`#fdcc52` 
`#fcbd20`
`#222222`
`#dd4b39`
`#1da1f2`
`#0d95e8`
`#3b5998`
`#344e86`
`#d73925`

**Comment by lguima** [comment]
Actually I was looking for the name of color scheme concept, but thank you anyway! :smiley:
