### ISSUE TITLE
Improvement for gh-pages compatibility

### ISSUE THREAD

**Issue by delsner** [BlackrockDigital/startbootstrap-new-age#6]
Since 2nd November 2016, gh-pages with running jekyll blog are per default ignoring `vendor` and `node_modules` folders (see https://github.com/blog/2277-what-s-new-in-github-pages-with-jekyll-3-3 ). So it's good to update the gulp inject task and name the folder something like `lib`. I'll create a PR when I have some time.

**Comment by delsner** [comment]
Solved in #7

**Comment by davidtmiller** [comment]
Merged.
